namespace Cinema.DTO.APIModels.MovieModel
{
    public partial class Movie
    {
        private const string IdName = "kinopoiskId",
            ImdbIdName = "imdbId",
            RusName = "nameRu",
            EngName = "nameEn",
            OrigName = "nameOriginal",
            PosterUrlName = "posterUrl",
            PosterUrlPreviewName = "posterUrlPreview",
            CoverUrlName = "coverUrl",
            LogoUrlName = "logoUrl",
            ReviewsCountName = "reviewsCount",
            RatingGoodReviewName = "ratingGoodReview",
            RatingGoodReviewVoteCountName = "ratingGoodReviewVoteCount",
            RatingName = "ratingKinopoisk",
            RatingVoteCountName = "ratingKinopoiskVoteCount",
            RatingImdbName = "ratingImdb",
            RatingImdbVoteCountName = "ratingImdbVoteCount",
            RatingFilmCriticsName = "ratingFilmCritics",
            RatingFilmCriticsVoteCountName = "ratingFilmCriticsVoteCount",
            RatingAwaitName = "ratingAwait",
            RatingAwaitCount = "ratingAwaitCount",
            RatingRussianCriticsName = "ratingRfCritics",
            RatingRussianCriticsVoteCountName = "ratingRfCriticsVoteCount",
            WebUrlName = "webUrl",
            CreationYearName = "year",
            FilmLengthName = "filmLength",
            FilmSloganName = "slogan",
            FilmDescriptionName = "description",
            FilmShortDescriptionName = "shortDescription",
            EditorAnnotationName = "editorAnnotation",
            IsTicketsAvailableName = "isTicketsAvailable",
            ProductionStatusName = "productionStatus",
            TypeName = "type",
            RatingMpaName = "ratingMpaa",
            RatingAgeLimitsName = "ratingAgeLimits",
            HasImaxName = "hasImax",
            Has3DName = "has3D",
            LastSyncName = "lastSync",
            CountriesName = "countries",
            GenresName = "genres",
            StartYearName = "startYear",
            EndYearName = "endYear",
            SerialName = "serial",
            ShortFilmName = "shortFilm",
            CompletedName = "completed",
            CountryName = "country",
            GenreName = "genre";
    }
}